export interface FormulaPresetModel {
  id: string;
  label: string;
  simulationName: string;
  formula: string;
  heroText?: string;
  guided?: boolean;
  primaryLabel: string;
  secondaryLabel: string;
  primaryColor?: string;
  secondaryColor?: string;
  particleRadius?: number;
  parameterValues?: Record<string, number>;
  summary: string;
}

export const FORMULA_SCENARIO_PRESETS: FormulaPresetModel[] = [
  {
    id: 'uniform-motion',
    label: 'MRU',
    simulationName: 'Movimento uniforme',
    formula: 'x = x0 + v*t',
    primaryLabel: 'Particula',
    secondaryLabel: 'Referencia',
    summary: 'Uma particula segue em linha reta com velocidade constante.',
  },
  {
    id: 'vertical-launch',
    label: 'Queda livre',
    simulationName: 'Lancamento vertical',
    formula: 'y = v0*t - (g*t^2)/2',
    primaryLabel: 'Corpo',
    secondaryLabel: 'Solo',
    summary: 'Altura e aceleracao gravitam para uma unica trajetoria vertical.',
  },
  {
    id: 'harmonic',
    label: 'Oscilacao',
    simulationName: 'Oscilacao harmonica',
    formula: 'x = A*cos(w*t)',
    primaryLabel: 'Oscilador',
    secondaryLabel: 'Centro',
    summary: 'O sistema alterna entre extremos e revela um padrao periodico.',
  },
  {
    id: 'gravity',
    label: 'Gravidade',
    simulationName: 'Dois corpos gravitacionais',
    formula: 'F = G * (m1 * m2) / r^2',
    primaryLabel: 'Corpo 1',
    secondaryLabel: 'Corpo 2',
    summary: 'Duas particulas interagem e mostram forca, rastro e aproximacao.',
  },
  {
    id: 'dynamics-incline',
    label: 'Plano',
    simulationName: 'Plano inclinado',
    formula: 'dynamics_incline = 0',
    heroText: 'Dinamica: plano inclinado',
    guided: true,
    primaryLabel: 'Bloco',
    secondaryLabel: 'Plano',
    primaryColor: '#ffb36c',
    secondaryColor: '#9dc7ff',
    parameterValues: {
      mass: 12,
      angleDeg: 28,
      g: 9.81,
    },
    summary: 'A massa, o angulo e a gravidade atualizam a decomposicao do peso em tempo real.',
  },
  {
    id: 'electro-coulomb',
    label: 'Coulomb',
    simulationName: 'Atracao entre cargas',
    formula: 'F = k*(q1*q2)/r^2',
    heroText: 'Eletromagnetismo: Coulomb',
    primaryLabel: 'Carga 1',
    secondaryLabel: 'Carga 2',
    primaryColor: '#ffb36c',
    secondaryColor: '#7ce6ff',
    parameterValues: {
      k: 42000,
      q1: 1.6,
      q2: -1.2,
      x1: -160,
      y1: 0,
      x2: 160,
      y2: 0,
    },
    summary: 'Cargas opostas se atraem e aceleram uma em direcao a outra.',
  },
  {
    id: 'electro-guided',
    label: 'Cargas',
    simulationName: 'Repulsao entre cargas',
    formula: 'electro_coulomb = 0',
    heroText: 'Eletromagnetismo: cargas',
    guided: true,
    primaryLabel: 'Carga +A',
    secondaryLabel: 'Carga +B',
    primaryColor: '#ff9d5c',
    secondaryColor: '#ffd166',
    parameterValues: {
      k: 42000,
      q1: 1.7,
      q2: 1.2,
      x1: -120,
      y1: -10,
      x2: 120,
      y2: 10,
    },
    summary: 'Duas cargas de mesmo sinal se repelem e se afastam no canvas.',
  },
  {
    id: 'electro-field',
    label: 'Campo',
    simulationName: 'Campo eletrico simples',
    formula: 'electro_field = 0',
    heroText: 'Eletromagnetismo: campo',
    guided: true,
    primaryLabel: 'Fonte',
    secondaryLabel: 'Sonda',
    primaryColor: '#ffb36c',
    secondaryColor: '#8ff7c1',
    parameterValues: {
      k: 48000,
      q1: 2.4,
      q2: 0.35,
      x1: 0,
      y1: 0,
      x2: 210,
      y2: 70,
    },
    summary: 'Uma carga fonte fica central e a sonda percorre um campo eletrico visual.',
  },
  {
    id: 'thermo-gas',
    label: 'Gas',
    simulationName: 'Gas ideal no recipiente',
    formula: 'thermo_gas = 0',
    heroText: 'Termodinamica: gas',
    guided: true,
    primaryLabel: 'Particulas',
    secondaryLabel: 'Recipiente',
    primaryColor: '#ffb36c',
    secondaryColor: '#9dc7ff',
    particleRadius: 7,
    parameterValues: {
      temperature: 420,
      volume: 82,
      particleCount: 24,
    },
    summary: 'Particulas se movem no recipiente e a velocidade cresce com a temperatura.',
  },
  {
    id: 'thermo-compression',
    label: 'Compressao',
    simulationName: 'Compressao termica',
    formula: 'thermo_compression = 0',
    heroText: 'Termodinamica: compressao',
    guided: true,
    primaryLabel: 'Particulas',
    secondaryLabel: 'Pistao',
    primaryColor: '#ff9d5c',
    secondaryColor: '#f4c66a',
    particleRadius: 7,
    parameterValues: {
      temperature: 520,
      volume: 52,
      particleCount: 30,
    },
    summary: 'O pistao altera o volume e deixa as particulas mais comprimidas no recipiente.',
  },
  {
    id: 'wave',
    label: 'Onda',
    simulationName: 'Onda viajante',
    formula: 'y = A*sin(k*x - w*t)',
    primaryLabel: 'Frente de onda',
    secondaryLabel: 'Eixo',
    summary: 'Uma onda periodica se propaga no espaco com amplitude e frequencia.',
  },
  {
    id: 'optics-reflection',
    label: 'Reflexao',
    simulationName: 'Reflexao plana',
    formula: 'optics_reflection = 0',
    heroText: 'Optica: reflexao',
    guided: true,
    primaryLabel: 'Fonte',
    secondaryLabel: 'Superficie',
    summary: 'Um raio incide em uma superficie plana e reflete com angulos simetricos.',
  },
  {
    id: 'optics-refraction',
    label: 'Refracao',
    simulationName: 'Refracao simples',
    formula: 'optics_refraction = 0',
    heroText: 'Optica: refracao',
    guided: true,
    primaryLabel: 'Fonte',
    secondaryLabel: 'Interface',
    summary: 'O raio muda de direcao ao cruzar uma interface com indices diferentes.',
  },
  {
    id: 'optics-lens',
    label: 'Lente',
    simulationName: 'Lente convergente',
    formula: 'optics_lens = 0',
    heroText: 'Optica: lente',
    guided: true,
    primaryLabel: 'Fonte',
    secondaryLabel: 'Lente',
    summary: 'Raios atravessam uma lente convergente e se aproximam do foco.',
  },
];
